site_name: TexnoMagic
site_url: https://texnoforge.github.io/texnomagic/
repo_name: texnoforge/texnomagic
repo_url: https://github.com/texnoforge/texnomagic
nav:
  - index.md
  - news.md
  - drawing.md
  - symbol.md
  - abc.md

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True

plugins:
  - search
  - autorefs
  - mkdocstrings

theme:
  name: material
  logo: img/x.png
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
