name: Docs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions-texnomagic[bot]
          git config user.email ci@noreply
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install deps
        run: |
          pip install .[png]
          pip install -r doc-requirements.txt
      - name: Link TexnoLatin to user alphabets path
        run: |
          ln -sr alphabets/texnolatin/ "$(texnomagic paths -a user --mkdir)"
          ls -la "$(texnomagic paths -a user)/texnolatin"
      - run: mkdocs gh-deploy --force
