name: Docs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions-texnomagic[bot]
          git config user.email ci@noreply
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install deps
        run: |
          pip install .
          pip install mkdocs-material
      - run: mkdocs gh-deploy --force
